Repository FabricElements/shared-helpers, pull requests merged in 2019-04, with the labels that each got.

#1 move from request-promise-native to node-fetch
  lib/api-request.js
  lib/api-request.js.map
  package.json
  src/api-request.ts
Labels: enhancement

#2 Add function random link domains
  lib/index.js
  lib/index.js.map
  lib/link-domain.js
  lib/link-domain.js.map
  lib/validate-url.js
  lib/validate-url.js.map
  lib/validateUrl.js.map
  src/index.ts
  src/link-domain.ts
  src/validate-url.ts
Labels: bug, enhancement

#3 Refactor Helpers
  lib/check-number.js
  lib/check-number.js.map
  lib/checkNumber.js
  lib/checkNumber.js.map
  lib/hash-id.js
  lib/hash-id.js.map
  lib/index.js
  lib/index.js.map
  lib/link-domain.js
  lib/link-domain.js.map
  lib/replace-message-text.js
  lib/replace-message-text.js.map
  lib/special-char-to-regular.js
  lib/special-char-to-regular.js.map
  lib/specialCharToRegular.js
  lib/specialCharToRegular.js.map
  lib/strings.js
  lib/strings.js.map
  lib/text-helpers.js
  lib/text-helpers.js.map
  lib/text.js
  lib/text.js.map
  lib/to-camel-case.js
  lib/to-camel-case.js.map
  package.json
  src/check-number.ts
  src/hash-id.ts
  src/index.ts
  src/link-domain.ts
  src/replace-message-text.ts
  src/special-char-to-regular.ts
  src/strings.ts
Labels: bug, enhancement

#4 Fix data types
  lib/replace-message-text.js
  lib/replace-message-text.js.map
  src/replace-message-text.ts
Labels: bug

#5 Add personalize domains to messages
  lib/replace-message-text.js
  lib/replace-message-text.js.map
  package.json
  src/replace-message-text.ts
Labels: enhancement
